### ISSUE TITLE
Error when running the script: KeyError: '2018-07-03'

### ISSUE THREAD

**Issue by aylen384** [jknphy/burndown_chart#1]
```
./burndown_chart.py 
[ 1] [functional][y][fast] Idea: y-team takes responsibility for daily review of yast2_ui scenarios on relevant products -> 1
Traceback (most recent call last):
  File "./burndown_chart.py", line 159, in <module>
    main()
  File "./burndown_chart.py", line 154, in main
    actual_remaining, total_story_points = calculate_burn(stories, sprint_info)
  File "./burndown_chart.py", line 143, in calculate_burn
    actual_remaining[dt.strftime(dt_format)]['value'] -= story_points
KeyError: '2018-07-03'
```

**Comment by jknphy** [comment]
https://github.com/jknphy/burndown_chart/commit/f60bd7adc8b54f3dd682825042fc40493cbe659a should fix this issue when some stories were closed one day before the start of the sprint but still listed my Redmine.
